{% set name = "jquery" %}
{% set version = "3.7.0" %}
{% set sha256 = "c7fd556ab7144e7d43cbd802fe63a07cd0d9f7442536ba57dbd44219efb06ebe" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jquery/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs

test:
  requires:
    - nodejs
  commands:
    - npm list -g jquery


about:
  home: https://github.com/jquery/jquery
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: jQuery JavaScript Library
  description: |
    jQuery JavaScript Library  
  doc_url: https://api.jquery.com/
  dev_url: https://github.com/jquery/jquery

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
