travis:
  secure:
    BINSTAR_TOKEN: jxzGIlvAiDNue/pMZz+COK571An4W2RtZBj9xlnW1G7xzHOwMWsnqdeNwBgixw5FpuogOvHOFaJdNuopYzU9TREgZYTdWl61HKThN/zjn5uZ7Zhe1+HTlMBB1nhFas2LEmHW6Culp778c6Xj/RmSpO+SmWINHz36mFMr8QTu0pZnVNJ0PdHMtdECti9X4/ebpi1QPb439Pa982iyuz9fiwwtPel0a1nmvq1du7ZN2IZsVlp+sKX0xn5G/ydRY4vfF15AHQsr087n2pKAnBbUpodRsB8mxqaYAGCpFMkmJWY8qv2LbeEcAmX2kKG4WsUmjs3Id06dXbqesrKCs4JSoWo9fQf746aBQfxRW79V4yNA7cgfjvboiOsRI6/3BikfcDJ+qwZGuVh/FfVP3YVvvh30HPktAeR01aJft1f1MgH3KE6e7tEOinFstMjcnh700NjPYAx5/pGBF+QB/FA1i5bA2/A7NkN3/xslhZCztN73iA+QrWm460N4vj1xuEhmE95INgJ/zBevifCLHYWvSkTvA7zBAI9u7IjG/4pZWFuCNxcYjrOVMbTp7FVL5i8Ky9mV7SU9eyizBgmebYJLubl1jJNzQbdoeHE2XQTOx6M6njHJzm2pNgUu16O5x1iaG36nE/cwI6PnKzE7+OiDbIqra6k8MvCmy2ydtuTMCXc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
